# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Publish

on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  build-pkg:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-dist
        path: dist/
  pypi-upload:
    runs-on: ubuntu-latest
    needs: build-pkg
    permissions:
      id-token: write
    environment: publish
    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v4
        with:
          name: release-dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
